<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DemoRestAdapter/FilePoller/AddMultiCustomer" name="AddMultiCustomer-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="AddMultiCustomer.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DemoRestAdapter/FilePoller/AddMultiCustomer"/>
    <wsdl:binding name="AddMultiCustomer_ptt-binding" type="add:AddMultiCustomer_ptt" xmlns:add="http://xmlns.oracle.com/pcbpel/adapter/db/DemoRestAdapter/FilePoller/AddMultiCustomer">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="insert">
            <soap:operation soapAction="insert"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>